STOP_WORDS = [
    "a", "about", "after", "again", "against", "all", "almost", "also", "although", "always", "am",
    "amount", "an", "and", "another", "any", "anyhow", "anyone", "anything", "anyway", "anywhere",
    "are", "around", "as", "at", "back", "be", "became", "because", "become", "becomes", "becoming",
    "been", "before", "beforehand", "being", "besides", "between", "beyond", "both", "but", "by",
    "can", "cannot", "cant", "could", "couldnt", "de", "describe", "detail", "do", "done", "down",
    "due", "during", "each", "eg", "eight", "either", "eleven", "else", "elsewhere", "empty",
    "enough", "etc", "even", "ever", "every", "everyone", "everything", "everywhere", "except",
    "few", "find", "first", "for", "former", "formerly", "found", "from", "front", "full",
    "further", "get", "give", "go", "had", "has", "hasnt", "have", "he", "hence", "her", "here",
    "hereafter", "hereby", "herein", "hereupon", "hers", "him", "his", "how", "however", "i", "ie",
    "if", "in", "inc", "indeed", "interest", "into", "is", "it", "its", "keep", "last", "latter",
    "latterly", "least", "less", "ltd", "made", "many", "may", "me", "meanwhile", "might", "mine",
    "more", "moreover", "most", "mostly", "move", "much", "must", "my", "name", "namely", "neither",
    "never", "nevertheless", "next", "no", "nobody", "none", "noone", "nor", "not", "nothing",
    "now", "nowhere", "of", "off", "often", "on", "once", "one", "only", "onto", "or", "other",
    "others", "otherwise", "our", "ours", "ourselves", "out", "over", "own", "part", "per",
    "perhaps", "put", "rather", "re", "same", "see", "seem", "seemed", "seeming", "seems",
    "serious", "several", "she", "should", "show", "side", "since", "so", "some", "somehow",
    "someone", "something", "sometime", "sometimes", "somewhere", "still", "such", "take", "than",
    "that", "the", "their", "them", "themselves", "then", "there", "thereafter", "thereby",
    "therefore", "therein", "thereupon", "these", "they", "thick", "thin", "this", "those",
    "though", "through", "throughout", "thru", "thus", "to", "together", "too", "top", "toward",
    "towards", "un", "under", "until", "up", "upon", "us", "very", "via", "was", "we", "well",
    "were", "what", "whatever", "when", "whence", "whenever", "where", "whereafter", "whereas",
    "whereby", "wherein", "whereupon", "wherever", "whether", "which", "while", "who", "whoever",
    "whole", "whom", "whose", "why", "will", "with", "within", "without", "would", "yet", "you",
    "your", "yours", "yourself", "yourselves"
]
